#Port number
server:
  port: 8989

#Application name
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PROJECT-SERVICE
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/projects/**
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
  config:
    import: optional:configserver:http://localhost:8885

#Eureka
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
